//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksAppMVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuthProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OAuthProfile()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public long Id { get; set; }
        public long RealmId { get; set; }
        public string AccessToken { get; set; }
        public string AccessSecret { get; set; }
        public string Datasource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
